= Aevum

(insert thought provoking quote here)

== What's all this, then?
Aevum is a new kind of novel. It combines elements of science fiction with speculative theology, and tells its bizarre story through both prose and classical epic poetry. Its contents aren't its only novel novel features: it is also open source, hosted on GitHub for anyone to copy, modify, critique, or contribute to.

=== Synopsis
I personally prefer to go into stories as blind as possible, but if you want a synopsis, here it is:

+++ <details><summary> +++
*Mild spoilers*
+++ </summary><div> +++
****
The story takes place in 2015, in Columbus, Ohio. We follow Grace, a college student studying to be a disaster relief medic. She has dreamed of doing heroic deeds since she was young, although until a few years ago, the deeds she envisioned were of a more fantastical nature than first aid. 

Her original idea was to be whisked away to another dimension, where she would doubtless prove instrumental in saving the world alongside a collection of beautiful, magical heroes. Some of them would probably even fall in love with her, so she made sure not to waste time dating any merely terrestrial candidates.

Of course, she didn't come up with these cringe-worthy ideas in a vacuum. She was simply an exceptionally optimistic product of the "Isekai" genre, wherein the premise invariably involves a normal protagonist from our world being magically transported to some other, much cooler world. You could pretty much sum it up by saying, "she watched too much anime."

Well, not long after she had finally given up on these notions, they actually come true! There is now real, undeniable proof of the sudden appearance of strange otherworldly people with incredible abilities. But unlike in her favorite shows, they don't show up directly in her path, but instead are stranded, hunted down, and wounded on the other side of the earth. Grace decides that this is her calling, so she embarks on a journey that risks everything to find them and help them. Perhaps she would finally become the savior she always wanted to be!?

But something is resisting her... dark, supernatural forces seem to have set themselves up against her, instilling dread and causing misfortune at every turn. Fell visions haunt her sleep, and deadly calamities plague her waking. She finds that she has thrust herself into the center of a conflict of a cosmic scale, involving powers far beyond her reckoning. Will her faith in herself be enough?

****
+++ </div></details> +++


=== License

I have selected a Creative Commons license for this novel. You can read it in its entirety link:LICENSE.md#[here], but the gist is that anyone can copy and modify the text as much as they want, except they can't use it for commercial purposes without permission.

I'm a software developer by day, and I know from first-hand experience that an open model of development yields better quality results tban a closed one. I care more about the quality of this story than I do about having all of the credit for writing it.

== Reading the things

On mobile, you might have to click "View code."

To read the current draft of the story, start reading each file under `story/` in numerical order, starting with 0. 

Poetic chapters are called _metrum_, and prosaic chapters are called _prosa_. I think it's Latin?

If you want to read ahead, there's a detailed outline in link:doc/notes.adoc[notes.adoc]. I tried to hide spoilers if you want to read through it, but it is primarily my author's notes, so it's meant to be thorough rather than dramatic. There are also character, place, philosophy, and history notes in there. 

== Collaboration

=== Contribution guide

I have our notes and our actual story written in the https://asciidoctor.org/docs/what-is-asciidoc/#what-is-asciidoc[AsciiDoc] file format. This gives us some powerful programmatic features that traditional .doc type files can't support. 

The most common consideration when contributing to a _metrum_ chapter is that AsciiDoc requires a `+` character to force a line break between two consecutive lines. I may eventually start using variables in the chapters, but not until GitHub https://github.com/github/markup/issues/1095[gets their act together.] Most of the interesting AsciiDoc stuff shows up in link:doc/notes.adoc#.

Speaking of which, if you want to try contributing substantial plot or dialogue, you need to be thoroughly familiar with that entire document. If you're just critiquing, helping with wording, or fixing typos, that's obviously not necessary.

Final warning: this may be open source, but I'm still very picky and opinionated! Contributions need to be top shelf to make it in. If I reject any proposed changes, I'll be sure to say why, and try to leave the door open if we can make it work. And I also want to be humble and receptive to criticism, or try to be open minded if a lot of people think a proposed change is an improvement on what I've written.

=== Discord

Join us on our https://discord.gg/BdbMaqYy[Discord channel], which is where the majority of our communication happens. Here are the channels so far:

*#aevum:* Whenever any changes or additions to the text happen, there will be a notification in the this channel. This is also where we can discuss the text.

*#aevum_meta:* This is for discussing the project at the project level, like about how to contribute, what's going on, etc.

=== Git and GitHub

The primary source material is and always will be hosted in a public git repository.

If you're unfamiliar with git, you can get a sense of what it does by watching https://youtu.be/OqmSzXDrJBk[this 5 minute video]. Just replace "software" with "book" and "code" with "text."

There are several reasons I chose git:

1. Change management is good for any complex, text-based work
1. Every time I push changes, it notifies the Discord channel. If you follow the link in the notification, you can see what changed. Commits can be viewed and commented on individually in GitHub, so collaborators and advisors can keep up with our progress.
1. All changes are preserved forever in a historical format. This enables interesting textual archaeology.
1. It allows for branching different versions of the text. This is nice for trying things out while developing the text, but also enables in a unique way a branching "multiverse" narrative. You can have multiple "timelines" exist in multiple branches in git. After the audience finishes reading the primary branch, they can use a diff comparison against other branches to see how they differ, and see other ways things could have turned out. It could give birth to a whole new breed of fanfiction.
1. It also powerfully enables collaboration. People can leave feedback via GitHub issues, which can be linked to actual text changes, and can also have "pull requests" attached to them where people can propose changes themselves. If anyone has an interest in doing so, they could wind up contributing a substantial amount to the end product.
1. Related to the above two points, there is the interesting fact that the GitHub collaboration model relies on "forking" (making a copy of) the repository. Anyone can fork the book and make their own edits to their own copy, essentially creating a new timeline in the multiverse. (I would maintain a list of canonical timelines, pointing to different forks that I believed were believable and worthy to be officially recognized.)
   
When complete, I will publish the book in print, ebook, and audiobook formats commercially. But the source text will always be available in a publicly-hosted git repository. The advantage of buying the story (when you could just read it here for free) would be a more pleasant reading experience, possibly even with pictures!

=== How to propose changes

First, you have to https://github.com/join[create a GitHub account]

If you see something that you think could be improved, you can open an https://github.com/InvokeAwesome/Aevum/issues[Issue].

If you have precise changes that you want to propose, you can do so https://docs.github.com/en/github/managing-files-in-a-repository/editing-files-in-another-users-repository[in the browser] without installing anything. 

If you're a power-user, you don't need any instructions on how to fork and clone the repo on your machine. Here's some https://docs.asciidoctor.org/asciidoctor/latest/tooling/[AsciiDoc tooling] you might find useful.