// Document
:toc2:
:toclevels: 4
:imagesdir: "images/"

// Main Character
:mc_name: Grace
:mc_surname: Ahn
:mc_heading: {mc_name} {mc_surname}
:mc_outset-age: 25
:mc_outset-location: Columbus, OH
:mc_ethnicity: Korean-American
:mc_native-language: Korean
:mc_trauma-age: 11
:mc_acceptance-age: 11th grade

// Mother
:mom_name: Min-ji
:mom_heading: {mom_name} {mc_surname}

// Sibling
:mc_sibling: younger brother
:mc_sibling-c: Younger Brother
:sib_gender: boy
:sib_name: Yoon
:sib_heading: {sib_name} {mc_surname}
:sib_pro: his
:sib_pro-c: His
:sib_trauma-age: 8

// Other world
:ow_group-nickname: B-Team
:ow_name: Floodless World
:ow_religion: Melchizidekian Divine Cult

// Other-worlder appearance in our world
:owa_location: Melbourne, Australia
:owa_month: July 

// Zack
:zk_true-name: Tsadq
:zk_nickname: Zack
:zk_outset-age: 295

// Eve
:ev_true-name: Hyav
:ev_nickname: Eve
:ev_outset-age: 295

// Jason
:js_nickname: Jason

// Raynor
:ry_nickname: Raynor

= Aevum Notes

== Plot Outline

=== Chapter {counter:chapters}

==== Style
Iambic hexameter couplets. Semi-elevated style. 

==== Setting 
A beautiful, wooded trail in the Appalachian Mountains. +
Midday.

==== Opening Characters
[horizontal]
*<<{mom_heading}, Mother>>*::
Hair in a ponytail  +
Wearing baseball cap, blue jeans, white tanktop  +
Carrying heavy hiking backpack  +

*<<{mc_heading}, {mc_trauma-age}-year-old girl>>*::
Hair in a ponytail similar to her mother's  +
Wearing a print T-shirt from last year's summer camp, pink cargo shorts.  +
Brand new shoes that are slightly too big.  +
Carrying a much smaller backpack filled with lightweight camping items 

*<<{sib_heading}, {sib_trauma-age}-year-old {sib_gender}>>*::
Hair messy. Bowl cut.  +
Star Trek print T-shirt  +
Sweatpants  +
Older shoes, starting to fray. White tube socks.  +
Glasses, low prescription

==== Narratitve

The above characters are hiking together along the side of a river, heading down the mountain.  +

They all stop to get a drink.  +

Mother [in {mc_native-language}]::
"Kids, come put your hand in this river! It feels amazing."

They do so, and it's surprisingly cold, like ice water.  +

They watch her take out a filter and process some water into their empty thermos jugs. +

They all take deep draughts. It's the most refreshing, delicious water they've ever tasted.  +

The young girl sits there for a while and watches the water flow over and around some rocks.  +

Up ahead, the stream splits into two different directions as it heads down the mountain. She watches with particular interest the point at which the stream bifurcates against a large, mossy boulder. +

After their break is done, they follow the left-hand branch of the river further down. They can start to hear the rushing of a waterfall. +

With increasing giddiness, the children start to pick up their pace. Their mother watches them contentedly. The roar of the waterfall gets louder. +

Finally they see it: although the waterfall is by no means impressive compared to some of the others in these mountains, it is the largest the children have ever seen personally. They both squeal with delight, and describe everything they see in great detail to their mother who is also standing right there and looking at it. +

She smiles at them and nods enthusiastically. +

Mother [in {mc_native-language}]::
"See what we've been missing? Aren't you glad Dad finally let us come out here?"

Children [in English]::
"YEAH!!" 

Mother [in {mc_native-language}]::
"Maybe we can convince him to come with us next time. What do you think?"

{mc_sibling-c} [alternating {mc_native-language} and English]::
Proceeds to optimistically describe the particular way in which their Dad would agree to do so.

The girl is more pensive, but is clearly imagining the scenario with glee.  +

They proceed downstream. +

They want to cross the river at the base of the falls, where it's thinner. +

Before they can do that, however, there is a fairly steep, 15-foot slope next to the waterfall that they must descend. There's no better point to descend nearby. +

The mother heads down first. She lowers herself down to a narrow ledge about 4 feet down. Then, facing the slope, she picks her way back and forth along a path of sorts, which proves to be easily navigable with some patience. She reaches the bottom in less than 15 seconds +

She then invites the children to come down. +

They were at first captivated by their cool mom and her feat of dexterity, but now that they realize that they too must make the descent, they are suddenly gripped by fear. +

Children [in {mc_native-language}]::
They complain, protesting the danger. 

Their small voices are almost drowned out by the sound of the waterfall, and they must shout to be heard. +

The mother surveys the descent again, pointing out the steps they must take. Raising her voice, she encourages them: +

Mother [in {mc_native-language}]::
 "I'm right here, guys! Even if you did fall, I'd catch you. But you won't fall, because you're really strong! {mc_name}, you can go first, to show your {mc_sibling} how it's done." +

{mc_name} [in English]::
Protests again +

Mother [in English]::
"You can do this, {mc_name}! It's gonna be OK." +

{mc_name} stares at the ground beneath her, as the beating of her heart swells in her ears above the roaring of the waters.


=== Chapter {counter:chapters}

==== Style
Basic prose with periodic stream-of-consciousness

==== Setting
A dimly-lit two-bedroom apartment, in the evening. +
It's midsummer (July) +
Living room has a 51" flascreen TV on a stand across from a cheap-looking couch

https://www.foxandhoundsaptsoh.com/apartments/oh/columbus/floor-plans#/categories/106111407/floorplans[Apartment Layout]

==== Opening Characters

[horizontal]
<<{mc_heading}, {mc_outset-age}-year-old woman:>>::
Hair in a messy bun, kind of frizzy. +
Wearing yellow shorts and a faded, black print T-shirt. The shirt has some obscure anime fandom reference. +
Has large, round, thin-framed silver glasses +
No makeup, no bra +
She's been home all day 


==== Narratitve
The setting sun peeks out behind some clouds, and shines brightly through the living room window, directly into the flatscreen TV. +

The young woman on the couch grumbles, enduring the situation for about 30 more seconds. +

As the sun does not cease its shining, she grumbles again and musters the willpower to get up and close the blinds. Now the picture on the TV is much clearer. +

She plops back down with a releived sigh to enjoy the fruit of her labors. +

There's some kind of fantasy anime playing on the TV: +

****
_Setting:_ +
Fantasy world with magic
Specifically, a generic European medieval village
The dialogue is in Japanese with English subtitles

_Opening Characters:_

[horizontal]
Protagonist::
A young man with generic brown hair and brown eyes +
Wearing a black-and-blue track suit +
Holding an over-designed and unwieldy-looking sword +
Average height +
Relatively thin build

Dragon::
30-feet tall +
European-style +
Black, scaley, muscular +
Red fire glows in its nostrils and in the back of its throat +
Eyes are bright, glaring +
Has an air of depraved, malicious intelligence

_Narrative_: +

The protagonist stares down a huge, black, demonic dragon. +

He seems to be the only one left standing between it and a small medieval-style village. All other defenders have been slain or have fled. +

The protagonist is panting, and sweating profusely. His hand trembles.  +

He remembers all of the times he ran away or faltered in combat. He remembers the many times he has had to be saved by this world's heroes. But this time, they are not here, not yet at least. +

He realizes that he could use a teleportation spell scroll in his pocket to escape, if he started the invocation now. But he's also keenly aware that, unlike him, the villagers here have nowhere to run. +

He takes a deep breath, grips his sword tightly, and makes his choice. +

Protagonist [in Japanese]::
Monologues at the dragon about his determination and how much he cares about the villagers and stuff. The delivery is horribly over-acted, and the lines are cheesy as hell.
****

The woman on the couch cringes a bit to herself, but her eyes remain locked on the screen to see what happens next. As the fight scene commences, she watches with quiet reverence.

****
_Narrative (cont'd):_ +

The protagonist holds his own for a little while, and a smile grows across his face. +

Protagonist [in Japanese]::
Predictably: "I can do this!" +

And predictably, it's right at that moment that his guard is broken and he receives a crushing blow to the chest. +

He's thrown violently into a wall, which caves in behind him from the impact. Blood erupts from his mouth, and he slumps to the ground. +

His vision goes in and out as he watches the dragon's slow, unstoppable approach. +

Pale, red fire glows in its nostrils, and the ground shakes with the sound of each titanic footfall. +

It stands over him for a moment, looking down with utter contempt at his feebleness. +

It raises a massive claw and brings it down towards him. +

But right at that moment, there is a blinding light, a slashing sound, and a brilliant white arc through its wrist. +

The claw falls to the ground, mere inches in front of the dying protagonist. +

_Character Introduced_: +
[horizontal]
Young woman::
Slightly taller than the protagonist +
Long, straight blonde hair +
Blue eyes +
Standard anime female facial features (pointy chin, big eyes, small nose, etc.) +
Silver circlet on her head +
Steel contoured breastplate, from which hangs studded leather strips about the waistin somewhat the style of a Roman legionary + 
Red miniskirt, slightly shorter than the leather strips +
Full-plate-style leg armor, up to mid-thigh +
Weilding a longsword, which emits a halo of faint purple light from the tip

_Narrative Continues_: +

[vertical]
Young woman [in Japanese]::
"Well done holding him off, Hibiki-kun!" +

The woman who dealt the blow says this while still hurtling through the air. +

She hits the ground in a kneeling posture between Hibiki and the dragon, which is now reeling back in pain. Her skirt flutters dramatically as the impact of her landing kicks up a ring of dust. +

She slowly raises herself and assumes a wide fighting stance +

Her breastplate glistens alternately in the purple light of her sword and the red light of the dragon's fire, and its blood is spattered on her face. +

She flicks her sword toward the ground, flinging the beast's dark gore in an arc away from her. +

With her other hand she flips her hair back into place

She glances back at Hibiki, and smiles.

Young woman [in Japanese]::
"Thank you for giving us enough time to get here. You've saved this village."

_Character Introduced_: +
[horizontal]
Elf woman::
Even taller than the first woman +
Has very long, elf-like ears +
Green eyes and hair +
Obnoxiously large breasts +
Wearing a skimpy costume that evokes a forest nymph, in about the same pattern as a one-piece bathing suit.


_Narrative Continues_: +
Another young woman lands next to him, using a magical force to slow her final descent before touching down gracefully. +

Her clothes flutter for a moment, and pale light surrounds her and the protagonist as she chants a healing spell. +

Feeling much better now, he stands up and joins the line as no less than five additional battle babes descend around him and proceed to hand the dragon his ass.

****

Meanwhile, the viewer has gotten up to get a glass of soy milk from the fridge, keeping her eye on the screen. +

She then spies the papers on the counter... her assignment for tomorrow's anatomy class. +

Viewer [in English]::
"Uhhh, oh yeah." She lets out a frustrated groan. "So much for tonight's binge."

She pauses the playback and turns off the TV. +

Her roommate instantly opens her bedroom door and peeks down the hallway.

_Character Introduced_: +
[horizontal]
<<{rm_heading}, Roommate>>::
Fairly short +
Sandy blonde hair +
Somewhat blemished complexion, well-hidden with makeup +
Wearing a white camisole and black shorts

[vertical]
Roommate::
"Hey {mc_name}, is the TV free?"

{mc_name}::
"Yeah, go for it."

{mc_name} walks back toward her own bedroom with the papers and her glass of milk.

She enters her room and closes the door

There is heard the muffled bickering of reality TV stars. +

She puts on some bluetooth headphones and starts her regular focusing playlist (consisting mostly of Japanese pop music and video game soundtracks.) +

She cracks open her laptop and starts banging away at the assignment, which is a clinical reasoning case:

* Physical trauma case in a disaster scenario.
* Struck on the head with rubble, right arm broken as well
* Dilated eyes
* Acting paranoid

As an aspiring disaster relief doctor, this is right up her alley. She is able to confidently answer several of the questions from memory, but eventually gets stuck and has to start scouring her textbooks. +

While she's flipping pages, she comes across a picture that reminds her of a scene from an https://en.wikipedia.org/wiki/Isekai[Isekai] anime show she used to adore back in middle school. She still loves this genre, and in fact the show she was watching just now was a recent example. +

Her brain dredges up favorite scenes, and she winces as she recalls the extent of her obsession. +

See <<Past Obsession with Isekai>>.

These thoughts lead inexorably to the same conclusion as always:

{mc_name} [thinking]::
It was all childish bullshit. I was a cringey, deluded idiot. There are no fantasy worlds, no magical heroes who will fall in love with me. It's pure escapism, meant to distract us from the bleakness of the real world for a few happy minutes, or hours. I bought in to it so deeply entirely because I wasn't happy with my life. How the hell did it take me until {mc_acceptance-age} to finally accept this?

She has gone through this exact thought process countless times, in the exact same sequence. On queue, she next notices her complusive face-touching, and went over what she had touched recently. +

She had been typing on her keyboard, which she can't remember wiping down recently, so she goes to wash her hands and face. +

That done, she stares at herself in the bathroom mirror, looking herself over. She adjusts her posture to best conceal the small paunch peeking out over her belt, and fusses with her black, straight hair. She wonders if she should go ahead and get double eyelids done at some point. +

She remembers the assignment, but she's getting really tired. She raps on the sink with her index finger while she runs some numbers. She could probably turn it in as is and get at least 7 of the 10 points it was worth. She's been pretty good with this class, she can afford it and still get an A, or A- at worst. +

She goes back into her room, turns off the lights, and flops in bed, still in her clothes. +

The belt's a bit uncomfortable so she awkwardly yanks it out and tosses it somewhere on the floor.

{mc_name} [thinking]::
Yeah, this is reality. This is what we have to work with. The closest thing I'll get to being a hero is helping people as a doctor, like Mom. Mom's a real hero, unlike those sword-swinging magical sex symbols.

She wonders with morbid curiosity if she could get away with wearing a miniskirt like that at church. +

She tries to recall the sermon from last Sunday. It takes about a minute of concentrated thought to bring up a vague theme about faith. +

There's one line she can remember clearly: "God does not owe you any more proof of his existence than the fact that you are here thinking about it." +

She turns the phrase over in her mind, as she considers all of the evidence in support of the fact that she is here through purely emergent processes. +

{mc_name} [thinking]::
Maybe God was also invented through an escapist impulse. Maybe people just couldn't deal with their own mortality and mundanity, so they wanted something more to be out there. 


+++ <details><summary> +++
*Hidden Motivations (Spoilers)*
+++ </summary><div> +++
****

Satan: He has been planning for {mc_name} to go to {ow_name} ever since he saw her obsessive personality start to form. He caused the hiking accident on their family's very first adventure because it would have the following effects:

1. Create discord and stress in the parents' otherwise excellent Christian marriage
1. Instill fear of death in {mc_name}'s heart, which would grow into full-blown hypochondria
1. Spark a desire in {mc_name} to become a "savior"
1. Her dissatisfaction with the real world and savior-fantasies pave the way for her isekai fascination 
1. Her disappointment with her Dad's timidity leads her to form an image of the "ideal man" that exactly matches {ry_nickname}.

God: All things work together for good to those who love Him:

1. He wants {mc_name} to become a doctor in order to save lives, principally, {js_name}'s life. This way, {ow_name} is not left without its greatest _Doctoris Ecclesiae_ during its most withering spiritual and geopolitical trial.
1. He also wants her to overcome her fears.
1. He permits her being drawn to {ow_name} (ultimately being the cause of so much chaos) because he actually wants to allow Satan's plan to succeed, nominally. {ow_name} has had too few trials, and has not fully learned the way of the cross.
****
+++ </div></details> +++


=== Chapter {counter:chapters}

==== Style

Heroic couplets again, but the language in this chapter is substantially more elevated than that of the first chapter.

==== Setting

{mc_name} is having an out-of-body experience.

==== Opening Characters

[horizontal]
<<{mc_heading}, {mc_name}:>>::
She is dressed in a white, floor-length robe, a white veil, and nothing else +
The robe is stained in several places +
Her hair is loose and floating as if submerged in water +
No glasses, but can see better than she would expect. Her vision is still somewhat blurry.

==== Narrative
{mc_name} sees her own spirit plotting its way through a chaotic temporal landscape. She looks up and sees a tether to what she senses is also her spirit looming over her, controlling her like a puppet. She then, further out of body, sees herself in this situation as a glittering string of sequential time states all at once. Then the strings unwind into a billion strands so small as to be indistinguishable. These stretch on ahead in many directions, coalescing into a crystalline ocean of possibilities, with waves that break against massive, impenermeable voids. She looks up to see a winged woman staring at her in this undulating space... the woman is not her, but sometimes she looks just like her for a split second. {mc_name} thinks she must be an angel.

The angel's gaze shifts to something behind her. {mc_name} turns and sees darkness and horror enveloping her, slashing and clawing and grasping for her with a thousand deformed hands. She tries to move away, but can't feel her legs. She tries to scream but can't make a sound. The only thing she can coherently remember about her life before this awful fear is a prayer her mother would say with her at bed time, when she was little. She tries to say the prayer aloud, but can only mouth the words with great difficulty.

Soon, as though sensing a predator approaching, the darkness hesitates, and then reluctantly retreats. A pale, and then blinding light appears, and a fiery, glowing hand lifts her up. A man's voice says, "Do not fear, little one." Her eyes, up until now being shut tightly with fear, and now because of the light, begin to open as the light moves away and inhabits a distant place, behind the crystal ocean.

The angel from before is seen standing up and removing her wings from covering her own head, and standing up from a prostrate bowing posture, facing where the light came from. There seems to be a floor now, or at least {mc_name} feels that "up" and "down" are meaningful again. A ripple in the sea is seen from a different direction, and a lesser but still brilliant light approaches. The angel again shields her face, but with only one wing. She bows, but does not prostrate herself this time. {mc_name} squints.

This new angel, appearing as an amorphous, fiery entity, looks at the first angel and asks a question in an unintelligible language. In reply, she points in the direction that the demon retreated. The second angel looks in that direction, then turns to {mc_name} as if he just noticed her. As he turns her direction, his appearance shifts to become first humanoid, and then fully human.

He stretches forth his hand at her. {mc_name} begins to fall at startling speeds. Earth and specifically her house and bedroom are beneath and she hurtles toward her sleeping body.

She wakes up screaming, in a cold sweat. She does not calm down for some time. She eventually begins to pray silently, her lips moving to the words of that same bedtime prayer, and she calms down. With her mind still trembling from the intensity and otherness of the experience, she gets up and turns on a lamp at her desk, but not before stumbling over some books on the floor.

She opens her laptop, and logs in, failing at the password five times, because her hands are shaking and her fingers are stiff. She closes an open web browser, opens a word editor, and writes down everything that happened. Though she struggles to find words to describe it, she remembers everything clearly. She spends a lot of time in prayer that night and doesn't fall back to sleep until two hours before she has to get up for school. (This is probably the most time she has spent in prayer in her entire life.)

+++ <details><summary> +++
*Hidden Motivations (Spoilers)*
+++ </summary><div> +++
****

Satan (apparent): It seems like Satan is trying to frighten {mc_name} away from {mc_name}'s mission. The spiritual attack comes the night before the {ow_group-nickname} show up. He apparently wants her to be tired and oppressed during those first crucial days, so that she misses her chance to find them.

Satan (actual): {mc_name} has many more spiritual and physical trials awaiting her. Satan wants her to feel like she's overcoming them against all odds. He wants her to feel like the heroine she always wanted to be. She will _still_ go after the {ow_group-nickname} despite her extreme fatigue and anxiety, because she is the determined heroine. She will quickly forget that it was only through the interposition of Christ that the demon was driven away.

Immediate Sin: *Pride*

God: Christ's brief words sum up exactly what God is doing here. He does indeed want her to overcome her fears, but through trust rather than self-reliance. He calls her "little one" to remind her of her total reliance on him. Sadly, she doesn't pick up on this until much later, but she will be humbled.

Eventual Virtue: *Humility*

****
+++ </div></details> +++

=== Chapter {counter:chapters}

Later that day, she falls asleep in class. Judging by her twitching, she was dreaming, and judging by her dumb unconscious smile, it was probably one of her childhood superheroes fantasies. The classmate next to her elbows her and she wakes up. The classmate tells her to look at what's on the screen of the laptop of the guy sitting in front of them. Dozens of other classmates, and even the professor, are gathered around, watching a news report. 

It tells about the sudden, inexplicable appearance of strangely-dressed people, one of them armed, who have caused great public alarm and thusfar avoided capture by using impossible abilities. There is an old man, a middle-aged man, and a young woman, and they appeared in a blinding flash of light in the middle of an intersection in {owa_location}.

The woman is dressed in something like armor, although it looks like it's something straight out of a science fiction game. She has what is unmistakably a futuristic assault weapon, and has used it to unleash a destructive power unthinkable for a weapon its size. She seems to not have intentionally killed anyone yet, but has destroyed roads and walls as they've made their escape from the SWAT teams sent to apprehend them. Bullets have been seen to deflect around her by virtue of a strange, barely-visible polygonal shape that surrounds her and moves with her. She can leap several stories at once and run at incredible speeds.

The middle-aged man is dressed in ornate vestments, possibly religious in character. He is also seemingly protected from projectiles by another invisible shield. He does not have any weapons, nor does he seem to have any special abilities. The woman shields him scrupulously, and carries him when she needs to leap or run quickly.

The old man wears very plain, uncomfortable-looking clothing. Aside from his well-trimmed beard, he seems almost like a beggar from a third-world country. The woman does not seem concerned with protecting him, yet he somehow consistently evades capture. Well, actually, he *has* been captured several times, because he never puts up any resistance. But each time, shortly after being detained, he disappears, sometimes reappearing with the other two. He has even been caught on camera simply opening the door of the police cruiser and just walking out, the handcuffs simply falling off, and no one seeming to notice him.

After watching for a bit and finally being convinced that it was all real, she bolts out of class and heads home. She begins to pack for her journey to find these people, because there is no doubt in her mind that these are the heroes she has always dreamed about.

+++ <details><summary> +++
*Hidden Motivations (Spoilers)*
+++ </summary><div> +++
****

Satan (apparent): The {ow_group-name} appears in our world very far away from {mc_name}, literally on the other side of the planet ({owa_location}). This is to make it seem as though he was trying to keep them as far away as possible from {mc_name}, because she holds the key to their return to {ow_name}.

Satan (actual): This is not the case. He wants her to take them (and herself) back to {ow_name} in order to give birth to the Nephilim through her, thus bringing the angels' ardent preservation of that timeline to an end. He places the {ow_group-name} as far away as possible from her to make it seem like a defensive choice, but he still picked a country with a language she can speak to make her task of finding and harboring them tractable. 

****
+++ </div></details> +++

=== Chapter {counter:chapters}

As she drives home, fatigue and anxiety encroach upon her. She's had less than two hours of sleep, just went through the most harrowing experience of her life, and on top of that, now reality itself seems to be turned on its head. She had just gotten over her childhood dreams, and now they suddenly come true?

She began her drive home filled with determination to not let this chance go. But as she drives home, her mind starts to fill with doubts. She talks aloud, trying to convince hersef to go:

"Could this have just been a well-crafted internet hoax?"

*"But there are so many sources... if it's fake it's impossible to tell. I have to look into it myself at this point, before they disappear."*

"Even if it's all real, what good would going there do? Why would they want anything to do with me?"

*"They looked like they were hurt, and they obviously can't stop at a hostpital. I have a world-class first-aid kit and I'm as good as a professional EMT. I can help them."*

"How will I keep up with them? I can't even run a quarter mile, let alone jump from building to building like that badass Space Marine chick. DAMN she's cool. Damn.

*"It looks like running is not what they need to do right now... they need to hide.  They probably don't have any money, don't know where they are, and don't speak the language. Everyone knows their faces. They need someone to keep them fed and out of sight. Good thing I'm loaded! Also good thing I spent all that time studying universal communication for this exact scenario, ha! HAHA! How is this happening??"*

"OK, but how do I get them to trust me? Obviously they need my help, but I'm a total stranger... how would they know that I'm not trying to lead them into a trap?"

*"Yeah that's a tough one, especially because the most effective way to detain them would be to plant an agent that can get to them while they're sleeping. The full-frontal attacks haven't been working obviously, because Xena over here kicks every ass in SIGHT. DAMN, girl!"*

*"...I don't know, they're probably desperate, and I look pretty harmless. I'm young and out of shape. Not exactly secret agent material. I'll just have to take my chances and be as helpful as possible."*

"Alright, saying they do take me in, what then? They're running for their lives. If we're found, I could be imprisoned and tortured, or maybe even killed..."

This gives her pause. 

She clenches her teeth. Her hands grip the wheel tighter. She stares at a single point on the road, all else fading out of focus, as her thoughts spiral downward.

She's brought back to reality by the blaring of a horn, from a sedan in the oncoming lane that's about to smash right through her. She veers back into her lane, almost side-swiping another car that's trying desperately to pass her. More horns. The tires screech as the car fish-tails, and she goes spinning into the shoulder.

=== Chapter {counter:chapters}



=== Spoilers follow



'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''

== Features of the Text

=== Style
(Most of?) the book will be written in iambic hexameter couplets, also known as "heroic couplets." This takes after the style of Alexander Pope (translating Homer) and John Dryden (translating Virgil). My goal is to resurrect classical epic poetry for our current cultural milieu, in a way that is aesthetically pleasing and accessible enough for the mainstream.

This is not just a gimmick, I hope, but serves a more immediate purpose for the narrative. The portions in verse are written from a heavenly, angelic perspective (see below), and the poetic format is intended to evoke that transcendence.

I should be able to achieve an earthly counterpoint to this by dropping into prose when the perspective shifts to that of a mortal human. Hopefully this will be evocative enough to reinforce the other narrative goals of the text.

=== Perspective
The portions of the book that are written in verse, are from perspective of {mc_name}'s guardian angel. We get a very intimate third-person view of {mc_name}, with impossible levels of detail. The angel can see things as minute as {mc_name}'s heart rate, body temperature, and the subtlest body language. We also sometimes have "educated guessing" about what she's thinking.

I think it may be important to make sure that we don't ever use definitive statements about what she's thinking, though. I don't think we want an unreliable narrator.

When this story was going to be told in game format, I had the player thinking that they were actually playing as {mc_name}, but then turn the tables when it's revealed that the player is actually her angel that has been guiding her. The twist is meaningful because the angel doesn't even realize it is a separate entity until that point.

In book format, though, I think we should still use third-person pronouns for {mc_name}. Doing otherwise might seem *too* jarring, and make the narrator unreliable.

=== Medium

The primary source material will continue to be hosted in a git repository.

There are a couple of reasons for this:

1. Change management is good for any complex, text-based work
1. Every time I push changes, it notifies the Discord channel. Commits can be viewed and commented on individually as well in GitHub, so collaborators and advisors can keep up with my progress.
1. All changes are preserved forever in a historical format. This enables interesting textual archaeology.
1. It allows for branching different versions of the text. This is nice for trying things out while developing the text, but also enables in a unique way a branching "multiverse" narrative. You can have multiple timelines exist in multiple branches in git. After the audience finishes reading the primary branch, they can use a diff comparison against other branches to see how they differ.
1. It also powerfully enables collaboration. People can leave feedback via GitHub issues, which can be linked to actual text changes, and can also have "pull requests" attached to them where people can propose changes themselves. If anyone has an interest in doing so, they could wind up contributing a substantial amount to the end product.
1. Related to the above two points, there is the interesting fact that the GitHub collaboration model relies on "forking" (making a copy of) the repository. Anyone can fork the book and make their own edits to their own copy, essentially creating a new timeline in the multiverse. (I would maintain a list of canonical timelines, pointing to different forks that I believed were believable and worthy to be officially recognized.)
   
When complete, I will publish the book in print, ebook, and audiobook formats commercially. But the source text will always be available in a publicly-hosted git repository. The advantage of buying the story (when you could just read it here for free) would be a more pleasant reading experience.


== Characters

=== {mc_heading}

==== Overview

She is {mc_outset-age}, in college, studying medicine as an undergrad in {mc_outset-location}.

She is a regular {mc_ethnicity} evangelical church-goer, but her faith is much less apparent Monday through Saturday

She has a {mc_sibling} named {sib_name}, that is in high school and still lives with their parents.

She drives a bus on campus as a part-time job.

==== Appearance 

She is {mc_ethnicity} American.

Her appearance is plain, and she’s a little bit pudgy.

She’s often frumped out due to laziness and a busy schedule, but she cleans up well enough.

==== History

She first started to become obsessed with the concept of the fantasy hero when she was young and started getting into anime and video games.

==== Past Obsession with Isekai
This went beyond merely enjoying the show and the genre broadly. She actually held on to a deep-seated belief that she would one day be swept off into another world, where she could live the fantasy that she was yearning for. Grace mentally rehearses all of the preparations she made, ranging from always carrying survival supplies to studying how to communicate with people who don't share a language with you. She tried her hand at things like marksmanship, martial arts, and even swordplay, but didn't have the discipline to keep up with them for long. (She still tells herself that she's just on hiatus from her martial arts, though.)

It took her until just recently to finally discard those notions and accept “real life.”

==== Motivations for studying medicine

* She is a hypochondriac and is deathly afraid of something being wrong with her body. It became exhausting and expensive to go see medical professionals constantly, so she decided to learn how to diagnose and treat herself.
* She figures that being a doctor is the best way to realistically play out her savior fantasies. She actually can learn how to save people’s lives, after all.

There are also historical reasons for both her hypochondria and her savior-obsession:

* When she was about {mc_trauma-age}, her mother, who was fairly adventurous, took their family hiking in some mountains. Her father, who was a cautious — or even nervous — person, was worried about the risks and didn’t want to go, but his wife insisted. Her {mc_sibling} ended up in a hiking accident and almost died, although fortunately her mother, who was an EMT, saved {sib_pro} life with some timely first-aid.
* After that, whenever her mother tried to make any ambitious plans for another adventure, her father would use the above incident as ammunition to shoot them down. They never really did any trips like it again.
* {mc_name} was influenced by this in that she admired her mother’s ability to save {sib_name}, but also saw how her father’s fears had been actually realized.

Her father and mother never separated or anything, and they do relate over a lot of things and statistically have a pretty good marriage. That said, the aforementioned hiking incident kind of killed off a good chunk of their relationship. Her mom feels tied down and not authorized to impart her adventurousness to her children. Her father lives in perpetual worry because of the way his wife takes risks, both professionally and whenever she gets the chance to sneak out on an unplanned adventure with her kids.

* {mc_name} and her {mc_sibling} of course picked right up on this. For {mc_name}, it made her want to build a better marriage, so she has very specific standards when it comes to men. She’s spent a lot of time thinking about that.
* She also has both adventurous and nervous tendencies. In any given situation, the side that wins out is dependent on how much time she has to think about the risks. (So she may jump into a risky situation on the spur of the moment, but if she's had enough time to think about it, she probably won't.)

==== Personality 

She’s smart, and retains information pretty well, but she struggles with diligence, academically speaking. She really does have everything it takes to be a decent doctor, but her grades suffer because of procrastination. She hates this about herself... but then she buys a shiny new indie game during a Steam sale and thinks, "Well, I'll focus better after I beat this." (She's also a completionist, so beating these games tends to take quite a while.)

She has many ambitions and many hobbies, but is a lot better at starting projects than finishing them.

Unlike either of her parents, who have been trapped in the lower-middle-class because of their spendthrift natures, she is actually rather prudent with her money. She is frugal almost to a fault, and has built up impressive savings for someone her age, despite paying for college largely on her own. This is how she was able to finance her eventual quest to find the "{ow_group-nickname}".

She is obsessive, so when she’s a fan of something, she’s a *big* fan. She will spend an amazing amount of time researching about and investing in her fandoms. 

She is sensitive and has a good sense of how other people feel, so she’s basically amiable and easy to like. However, she often struggles to care about or do anything out of her way to actually address the negative feelings she senses in other people.


=== {mom_heading}




'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''
'''


=== {zk_nickname}

==== Name

"{zk_true-name}” comes from the semitic root `ṣdq`, which finds itself in the Hebrew word “Zadok” and others. It denotes the idea of “righteousness.” He’ll go by “{zk_nickname}” in our world when he gets here.

==== Overview

He is the recently-elected chief pontiff of the {ow_religion} in the floodless world. As an analogue to the Pope in our world, he carries a political clout on par with the Papacy at its height in the Middle Ages, complete with sovereignity over some small but valuable territories.

He is {zk_outset-age} years old (born on the same day as Eve.)

He is married to Eve, who is his bodyguard and third cousin.

==== Appearance

Up until somewhat recently, he really cared about his physical shape and health. He got himself pretty fit at one point. However the last year has been so stressful that he has let himself go. So he’s got a bit of a beer gut coming and his muscles have atrophied to some extent. But you can still see evidence of muscle tone from his fitness days, especially in his arms. He should faintly resemble Eve, maybe in his hair or eye color. (They're distantly related.)

Floodless people his age usually look around their late 30s / early 40s to us and stay that way for a very long time, only showing increased signs of aging around the 650s.

==== History

He and Eve have known each other since childhood, due to their close kinship and the extreme regard for familial relationships in their culture.

Because his parents were particularly well-positioned and well-respected in the upper echelons of the church, there was always a very good chance that he would become the chief pontiff someday. There had been several pontiffs among his direct ancestors, in fact.

Eve’s attention towards him could not go unnoticed. She had inserted herself so inexorably into his daily affairs for such a long time that the thought of life without her rarely crossed his mind. When it did, it was always unpleasant to him, because Eve had done a remarkable job of responding to his goals, habits, and preferences. He had neither need nor desire to look anywhere else for a partner and mate.

However, as it was becoming increasingly apparent n his early 50s that the office of chief pontiff would one day fall to him, he received pressure to remain celibate from his parents and other powerful members of his family. For a long time now, pontiffs had all maintained celibacy, to the point that it was now customary. His family didn’t want him to ruin his odds by marrying Eve.

But {zk_nickname} is an idealist, and wrestles with himself a great deal when it comes to optimal long-term decision-making. Eve had made herself the absolute prime choice to be his bodyguard, and he was paranoid to a fault about his personal safety, so he wanted her to be with him all the time. (See Eve's doc for how and why she did this.) This wouldn't have been so hard if the "optimal candidate" had been a man, but it is completely taboo in their culture to cohabitate with the opposite sex, even in a professional capacity. (And, frankly, he was completely infatuated with her. How could he not be?)

He decided that he would remain celibate until he took the throne, and then select her as his bodyguard in a merely professional capacity. He was betting that public opinion would shift towards wanting him to just go ahead and marry her, as it would seem scandalous to have her around all the time and yet be unmarried.

(It should be noted that celibacy was not yet a canonical discipline in this church, but simply a very well-established custom. Long ago, priests would sometimes marry after their ordination, and there was even one historical example of a chief pontiff doing so. This was done only on an exceptional basis, and usually had to do with an urgent necessity to preserve a family's patrilineage. {zk_nickname} happened to also be in this situation, being the only son in his immediate family, which lent legitimacy to the move.)

After 200 years, {zk_nickname} was finally elevated to the office he desired. His plan to justify a marriage worked, and the damage to his reputation was only temporary. Even in the first few months of his reign, Eve’s constant presence had saved his life a few times in really spectacular ways, which would not have been possible unless they lived together. Since things were working out really well, the public got used to having a married pontiff again.

Every one of pontiffs in recent memory had been assassinated within a decade of taking office, but with Eve at the head of his retinue, even the most sophisticated, multi-pronged attacks to date were thwarted in style. The political stability afforded by the arrangement paid off in spades for their public esteem.

They became so popular, in fact, that certain factions wanted to set them up as titular monarchs. Their civilization was mostly held together by an Old Testament-style system of theocratic Judges overlayed on a network of city-state alliances. This system was losing credibility in modern political discourse, and the tide had been growing for some time now in favor of a unified monarchy. (While the chief pontiff enjoyed a great deal of political influence, he did not have direct authority over the secular management of most territories in the realm.) The stability and charisma of {zk_nickname} and Eve became the icon for this movement, and they had successfully worked themselves into the center of it.

Though there isn’t a precedent for a unifying monarchy in their society, more distant kingdoms have tried it and have done well enough to provoke local envy.

==== Personality

{zk_nickname} is analytical, chatty, and a perfectionist. Like most perfectionists, he strives to correct any perceived fault in himself, and can't understand why others would fail to do the same.

He constantly overthinks things, yet has a natural tendency to let his mouth move faster than his brain. However, he has tempered that flaw over his many years, and developed the habit of pausing intentionally for at least three seconds before saying anything other than an innocuous question. He forgets that habit when he’s tired or hungry or emotionally unstable, and can say hurtful, critical things before he has a chance to catch himself. He also regularly stops mid-sentence to re-phrase his thoughts more precisely, so talking to him can be tiresome for those used to a more natural flow of conversation.

Though he tries to be careful with his words, he is inquisitive to a fault. He's usually the one driving conversations, mostly by asking a lot of overly-specific questions. This can make people uncomfortable, as he tends to "pry."

It should be noted that these flaws are mostly manifested in private conversation. In public addresses he's an absolute rock star.

He inwardly has a high opinion of himself, and despite toning down his pride outwardly, he still harbors an inveterate superiority complex.

He used to be a pretty big jerk because of his pride and critical nature, but has become more likable after intentionally refining his personality for a long time. Eve has been an essential part of this transformation, as she honestly and bluntly points out his unlikable qualities. Far from driving him away, this behavior has increased his opinion of her to even greater heights.

However, despite his carefully-groomed external charisma, nothing about him is charitable. Everything he does is ultimately for himself, and he often uses others to his own advantage. His preference is to find a “win-win,” but he doesn’t hesitate to step on people when such a solution can't be found. His relationship with Eve is one such "win-win," but he has grown so accustomed to viewing her as an asset that he scarcely ever looks at her through the eyes of selfless love.


=== Eve

==== Name 
“{ev_true-name}” comes from the semitic root ḥyw, from which the biblical Eve derives her name (“Havah” or “Hawwah”). It means “life,” i.e. "Mother of all the Living" for the biblical Eve.

==== Origin
Floodless world, near the capital

==== Overview
She is the bodyguard of Tsadq (Zack), the chief pontiff of her people’s religion.

She is enjoys a high degree of popular favor due to her amazing super-soldier abilities, having successfully defended the pontiff from every assassination attempt to date. (This is an unprecedented feat. Almost every recent pontiff has either been assassinated or resigned out of fear of a plot. Eve is thus directly responsible for a marked improvement in the political stability of the realm.)

She is mute. No one knows exactly why, but her brain does show some physiological abnormalities.

She is 295 years old (born on the same day as Zack)

She is also married to Zack, the chief pontiff, who is also her third cousin.

==== Appearance
Due to her extreme enhancements and training, she is abnormally muscular. Some cybernetic implants are visible as bumps just under the skin.

She makes every effort to accentuate her physical strength through her dress and bearing. (This is typical behavior for warriors in their culture, although it is traditionally a masculine pursuit.)

Due to the stress of Zack’s recent climb towards monarchical power, she has spent less time training recently. Nevertheless, her genetic, cybernetic, and nanotech enhancements maintain much of her body’s strength and fitness. She wears her full battle suit constantly whenever leaving their fortress.

Though at her age she should look to be in her late 30s or early 40s, she has had countless medical anti-aging procedures. (These only became available recently). It has mostly worked, but there are still some lines she can’t quite erase without looking fake. (Imagine a pretty 25-year-old who has been smoking for a few years, and you'll get the picture.)

==== History
She and Zack have known each other since childhood, due to their close kinship and the extreme regard for familial relationships in their culture.

She was still in her minority when she realized how great Zack’s potential for success was. Despite not being terribly analytical, she had a strong sense of intuition that told her that, if she could make herself an essential part of his life, she would benefit herself greatly.

So even as a child, she made sure she spent as much time playing with him as possible, and paid very close attention to his likes and dislikes. She endeavored to adapt herself to become exactly what he wanted and needed: mentally and physically; socially and pragmatically. Because of his idealism and "optimize everything" approach to life, she knew that if she could simply make herself the most "optimal" choice for his wife, then her victory would be assured.

Being mute, she was an excellent listener, and Zack always loved to ramble to her about whatever he was learning or improving about himself. To him, her constant, persistent, intentional, and undivided attention was soothing, and addictive. Speaking to her has always been as natural and vital to him as breathing.

Her ability to communicate improved along with technology, and she always mastered the current cutting-edge text-to-speech software. By the time our story starts, she can “speak” with an almost-natural-sounding computer voice by flitting her fingers as input, as though typing on an invisible keyboard.

As pontiffs started getting assassinated one after another, she could see Zack's paranoia kick into full gear as he strove towards becoming a candidate. Much of his time was spent researching self-defense methods and the latest technology, so naturally she decided to make herself the best possible defense for him. She underwent experimental super-soldier enhancements and training, integrating every means of increasing her strength that was available to her (no matter how dangerous or unproven or illegal.) Miraculously, almost every enhancement succeeded brilliantly, and she eventually became regarded as the strongest and deadliest single individual on the planet.

Her efforts paid off (see Zack’s doc).

After Zack took office, her public popularity and influence in his cabinet skyrocketed with every thwarted assassination attempt. She became a pop-culture icon with an avid fan following. Because she essentially resurrected the long-defunct, traditional vestments that wives of clergy used to wear during formal ceremonies, top clothing brands picked up on the style for streetwear. It's pretty trendy now.

The high-profile nature of her successful enhancements also catalyzed the deregulation and advancement of transhuman enhancements globally. The assassination attempts had died out for a while, but began to increase again as more people gained access to the same technologies she had. But between unlimited funding, a team of the country’s best people, superior intel, her ever-sharpening experience, and a genius for combat that flowed from her instinctive nature, no one could best her. Zack was all too pleased.

She prioritized her capacity as a bodyguard over her capacity to be a mother. Pontiffs have traditionally been celibate, and Zack broke sharply with tradition by taking a wife. (See his doc for why he did this.) Pontiffs were not expected to have children and were canonically forbidden from appointing heirs to their position. Thus, childbearing was far from desirable for Eve, because it would not only take her out of commission, but cause their marriage's tenuous political legitimacy to come under fire again. Despite the cultural and dogmatic taboo on the procedure, she had herself secretly sterilized. Publicly they said that they were simply not successful at having children, and she was assumed to be naturally barren.

==== Personality
She is acutely empathetic and circumspect. She has spent far more time listening than expressing (because of her muteness), but this is only one cause of this trait. She is also more outwardly-focused by nature, and has little in the way of personality traits that are distinctively her own. Her personality is mostly made to match what she perceives others (chiefly, Zack) want from her.

But there are some insuppressible quirks that are definitively hers:

* Her sense of humor is subtle, but mischievous. This is the only way in which she actively and intentionally flusters other people, rather than trying to please them. She hasn’t been able to talk until recently (and even now, talks only rarely), so this usually manifests in either practical jokes or ornery body language.
* She can usually guess when those actions will ultimately improve or damage her relationships, so she uses them judiciously (not at the expense of endearing herself in the long run).
* If she misjudges and plays a prank that only serves to be aggravating (or behaves impishly when sobriety is called for), she gets sulky. She rarely apologizes until roughly 6 hours have elapsed. Her apologies are always handwritten, anonymous, and delivered covertly.

Finally, everything she does is 100% self-motivated. The people-pleasing is all about improving her standing, influence, or self-satisfaction. She is devoid of altruistic or charitable feeling.

* She is by no means of a logical disposition, and so cannot be considered “calculating” with her actions. Rather than planning and manipulating, she more or less intuits how best to modify herself to maximize her public esteem.
* But the targets of her attention and service are carefully selected based on the degree to which she thinks they can elevate her. Once she decided that Zack was her best shot, she spent very little time or energy trying to please anyone else.

=== Jason

==== Name 
Haven't settled on a name yet. The character is vaguely derived from a "Jason" from the original story so I'll go with that for now.

==== Overview
He is one of 120 Old-Testament-style “Judges” in the same civilization as Zack and Eve.

He is 823 years old

He is the oldest and most revered of the Judges. The miraculous signs he has performed are some of the most famous to date, and many of his written works are considered scripture by some theological schools. (As in our world, canonization is a slow process and settles over time).

==== History
Jason has only officially held the office for about 200 years, but ever since his adolescence (50s) he has been considered a prophet.

The early days of his spiritual journey were marked by a vow of celibacy and intense asceticism. There are many monastic orders, but he was called to a more solitary existence. For most of the year, he would survive alone in the wilderness, praying and fasting and writing down his visions and insights. Once every new moon he would come to the capital city and preach, also sharing his written works (some of which were epistles, some poetry, and nearly all of them copied and published right away.)

People often tried to follow him back into the wilderness, but he was always spirited away and could never be found. Still, he had many imitators and rivals.

It took a long time before he was appointed to be a Judge. (Too long, according to his fans and devotees). He never sought the office, and actually took it grudgingly at first, but soon came to find joy in his new form of ministry.

Judges here are a more developed and established version of our Old Testament Judges, with a more formally defined office that centers around mediating between the city states. The office of Judge also somewhat resembles that of the Roman censor, insofar as they have the right to expel government officials for immoral behavior. They also have veto powers over local legislation if it is deemed to be morally compromised.

It should be noted that the aforementioned roles and powers are highly regionalized, and not consistent across the realm. The above pattern is common, but their authority derives entirely from historical contingencies and legal precedents. The culture is diverse from region to region, and the customs surrounding the Judges vary. That said, any Judge is automatically given deferential treatment in any region, and their office is universally honored at least in form if not in substance. For example, if a Judge was travelling to another jurisdiction and pronounced a judgement that would be accepted without question in his own jurisdiction, the local officials would at least formally accept his decision, even if they don't intend to actually implement it. They would probably later oficially excuse themselves based on "unforeseen circumstances" or otherwise write up an elaborate loophole.

The 120 Judges are on paper considered to have the highest official administrative power, but it would be an overstatement to say that they “rule” their regions. The real power his held by various local magistrates and oligarchs, along with wealthy family-syndicates. The Judges realistically only hold sway insofar as the public’s admiration of them allows.

They are theocratically appointed, using ritualistic processes of divination that vary per region. Their appointment is usually heavily influenced by the priesthood, and must be confirmed by the chief pontiff. (Although if a pontiff rejects a candidate for any remotely questionable reason, it has historically been seen as an overstepping of his customary bounds and is tolerated only grumblingly by the people.) As in Jason’s case, they often double as prophets, some of whom are on par with prophets like our Elijah (along with the commensurate miraculous signs).

The Judges have been generally well-esteemed until about a year ago, when public opinion began to shift in favor of a unified monarchy (with Zack and Eve as the intended King and Queen.) There has always been ambiguity in the authority structure of the Judges, but recently there have also been suspicions of some Judges being falsely appointed, having allegedly paid off certain key clergy to gain the office.


== Spoilery notes for sorting

=== {mc_name} {mc_surname}

This is integral to her eventual success at tracking down the {ow_group-nickname}.

She is completely dissatisfied with “real” life, hence the Isekai fixation. This isn't tied to any particular incident, but she is admittedly unhappy with her family's dysfunction and perpetual teetering on the brink of poverty. She also can't find any men who fit her standards in this world, (or at least that's her excuse for never quite locking down a date.) But there's an even simpler explanation for her longing for other worlds: it started as plain old chuunibyou, and her uniquely obsessive personality just latched on really hard and didn't let go.

The {ow_group-nickname} and their world is only the first part of how we see this fixation play out in a practical way. When she finds out about her angel, and the vastness of the spiritual realm, she almost completely neglects everything mundane (including her family, and even the {ow_group-nickname} itself eventually). Unfortunately, this does not mean she becomes fixated on God himself, but rather merely the “otherness” of the fullness of his creation.

