include::doc/vars.adoc[]

=== Name
"Tsadq” comes from the semitic root `ṣdq`, which finds itself in the Hebrew word
“Zadok” and others. It denotes the idea of “righteousness.” He’ll go by “Zack” in
the US when he gets here.

=== Place in life at outset
He is the recently-elected chief pontiff of the Melchizedekian cult in the
floodless world. As an analogue to the Pope in our world, he carries a political
clout on par with the Papacy at its height in the Middle Ages, complete with
sovereignity over some small but valuable territories.

He is {zk_outset-age} years old (born on the same day as Eve.)

He is married to Eve, who is his bodyguard and third cousin.

=== Appearance
Up until somewhat recently, he really cared about his physical shape and health.
He got himself pretty fit at one point. However the last year has been so
stressful that he has let himself go. So he’s got a bit of a beer gut coming and
his muscles have atrophied to some extent. But you can still see evidence of
muscle tone from his fitness days, especially in his arms. He should faintly
resemble Eve, maybe in his hair or eye color. (They're distantly related.)

Floodless people his age usually look around their late 30s / early 40s to us
and stay that way for a very long time, only showing increased signs of aging
around the 650s.

=== History and character development
He and Eve have known each other since childhood, due to their close kinship and
the extreme regard for familial relationships in their culture.

Because his parents were particularly well-positioned and well-respected in the
upper echelons of the church, there was always a very good chance that he would
become the chief pontiff someday. There had been several pontiffs among his
direct ancestors, in fact.

Eve’s attention towards him could not go unnoticed. She had inserted herself so
inexorably into his daily affairs for such a long time that the thought of life
without her rarely crossed his mind. When it did, it was always unpleasant to
him, because Eve had done a remarkable job of responding to his goals, habits,
and preferences. He had neither need nor desire to look anywhere else for a
partner and mate.

However, as it was becoming increasingly apparent n his early 50s that the
office of chief pontiff would one day fall to him, he received pressure to
remain celibate from his parents and other powerful members of his family. For a
long time now, pontiffs had all maintained celibacy, to the point that it was
now customary. His family didn’t want him to ruin his odds by marrying Eve.

But Zack is an idealist, and wrestles with himself a great deal when it comes to
optimal long-term decision-making. Eve had made herself the absolute prime
choice to be his bodyguard, and he was paranoid to a fault about his personal
safety, so he wanted her to be with him all the time. (See Eve's doc for how and
why she did this.) This wouldn't have been so hard if the "optimal candidate"
had been a man, but it is completely taboo in their culture to cohabitate with
the opposite sex, even in a professional capacity. (And, frankly, he was
completely infatuated with her. How could he not be?)

He decided that he would remain celibate until he took the throne, and then
select her as his bodyguard in a merely professional capacity. He was betting
that public opinion would shift towards wanting him to just go ahead and marry
her, as it would seem scandalous to have her around all the time and yet be
unmarried.

(It should be noted that celibacy was not yet a canonical discipline in this
church, but simply a very well-established custom. Long ago, priests would
sometimes marry after their ordination, and there was even one historical
example of a chief pontiff doing so. This was done only on an exceptional basis,
and usually had to do with an urgent necessity to preserve a family's
patrilineage. Zack happened to also be in this situation, being the only son in
his immediate family, which lent legitimacy to the move.)

After 200 years, Zack was finally elevated to the office he desired. His plan to
justify a marriage worked, and the damage to his reputation was only temporary.
Even in the first few months of his reign, Eve’s constant presence had saved his
life a few times in really spectacular ways, which would not have been possible
unless they lived together. Since things were working out really well, the
public got used to having a married pontiff again.

Every one of pontiffs in recent memory had been assassinated within a decade of
taking office, but with Eve at the head of his retinue, even the most
sophisticated, multi-pronged attacks to date were thwarted in style. The
political stability afforded by the arrangement paid off in spades for their
public esteem.

They became so popular, in fact, that certain factions wanted to set them up as
titular monarchs. Their civilization was mostly held together by an Old
Testament-style system of theocratic Judges overlayed on a network of city-state
alliances. This system was losing credibility in modern political discourse, and
the tide had been growing for some time now in favor of a unified monarchy.
(While the chief pontiff enjoyed a great deal of political influence, he did not
have direct authority over the secular management of most territories in the
realm.) The stability and charisma of Zack and Eve became the icon for this
movement, and they had successfully worked themselves into the center of it.

Though there isn’t a precedent for a unifying monarchy in their society, more
distant kingdoms have tried it and have done well enough to provoke local envy.

=== Innate personality
Zack is analytical, chatty, and a perfectionist. Like most perfectionists, he
strives to correct any perceived fault in himself, and can't understand why
others would fail to do the same. 

He constantly overthinks things, yet has a natural tendency to let his mouth
move faster than his brain. However, he has tempered that flaw over his many
years, and developed the habit of pausing intentionally for at least three
seconds before saying anything other than an innocuous question. He forgets that
habit when he’s tired or hungry or emotionally unstable, and can say hurtful,
critical things before he has a chance to catch himself. He also regularly stops
mid-sentence to re-phrase his thoughts more precisely, so talking to him can be
tiresome for those used to a more natural flow of conversation.

Though he tries to be careful with his words, he is inquisitive to a fault. He's
usually the one driving conversations, mostly by asking a lot of overly-specific
questions. This can make people uncomfortable, as he tends to "pry."

It should be noted that these flaws are mostly manifested in private
conversation. In public addresses he's an absolute rock star.

He inwardly has a high opinion of himself, and despite toning down his pride
outwardly, he still harbors an inveterate superiority complex.

He used to be a pretty big jerk because of his pride and critical nature, but
has become more likable after intentionally refining his personality for a long
time. Eve has been an essential part of this transformation, as she honestly and
bluntly points out his unlikable qualities. Far from driving him away, this
behavior has increased his opinion of her to even greater heights.

However, despite his carefully-groomed external charisma, nothing about him is
charitable. Everything he does is ultimately for himself, and he often uses
others to his own advantage. His preference is to find a “win-win,” but he
doesn’t hesitate to step on people when such a solution can't be found. His
relationship with Eve is one such "win-win," but he has grown so accustomed to
viewing her as an asset that he scarcely ever looks at her through the eyes of
selfless love.
